version: '2.0'
services:

  mariadb:
    container_name: 'mariadb'
    image: mariadb:latest
    networks: 
    - vaccinations
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
    restart: unless-stopped
    volumes:
      - /home/flatly/apps/mariadb:/var/lib/mysql

  swag:
    container_name: swag
    image: ghcr.io/linuxserver/swag
    networks:
    - vaccinations
    cap_add:
    - NET_ADMIN
    restart: unless-stopped
    volumes:
    - ./nginx/site-confs:/config/nginx/site-confs
    - ./nginx/proxy-confs:/config/nginx/proxy-confs
    - /home/flatly/apps/www:/config/www
    - ./nginx/cert:/config/dns-conf/
    ports:
    - 443:443
    - 80:80
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Warsaw
    - URL=szczepienia.pw
    - SUBDOMAINS=www,develop,jenkins,phpmyadmin,backend,develop-backend
    - VALIDATION=dns
    - DNSPLUGIN=cloudflare
    - DUCKDNSTOKEN=e68c855a-e1d6-4da3-ac66-0443bc4bf250
    extra_hosts:
    - "host.docker.internal:host-gateway"

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    networks:
    - vaccinations
    restart: unless-stopped
    volumes:
    - /home/flatly/apps/jenkins:/var/jenkins_home

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    networks:
    - vaccinations
    restart: unless-stopped
    environment:
      PMA_HOST: 'mariadb'

  vue:
    container_name: vue
    build:
      context: ./scripts 
      dockerfile: ../containers/vue/Dockerfile
    volumes:
      - /home/flatly/:/app/
    image: vue
    networks: 
      - vaccinations
    restart: unless-stopped

  dotnet:
    container_name: dotnet
    build:
      context: ./scripts
      dockerfile: ../containers/dotnet/Dockerfile
    volumes:
      - /home/flatly/apps/dotnet:/app/
    image: dotnet
    networks: 
      - vaccinations
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./containers/backend/
      dockerfile: ./Dockerfile
    image: backend
    volumes:
      - /home/flatly/apps/dotnet/main:/app
    networks: 
      - vaccinations
    restart: unless-stopped

  backend-develop:
    container_name: backend-develop
    build:
      context: ./containers/backend/
      dockerfile: ./Dockerfile
    image: backend-develop
    volumes:
      - /home/flatly/apps/dotnet/develop:/app
    networks: 
      - vaccinations
    restart: unless-stopped

  cross:
    container_name: cross
    build:
      context: ./containers/cross/
      dockerfile: ./Dockerfile
    image: backend
    networks: 
      - vaccinations
    restart: unless-stopped

networks:
  vaccinations:
