version: '3.8'
services:

  mariadb:
    container_name: 'mariadb'
    image: mariadb:latest
    networks: 
    - vaccinations
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
    restart: unless-stopped

  swag:
    container_name: swag
    image: ghcr.io/linuxserver/swag
    networks:
    - vaccinations
    cap_add:
    - NET_ADMIN
    restart: unless-stopped
    volumes:
    - ./nginx:/config/nginx
    - /home/flatly/drop_zone/www:/config/www
    ports:
    - 443:443
    - 80:80
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Warsaw
    - URL=flatly.online
    - SUBDOMAINS=www,develop,jenkins,phpmyadmin,backend,doctor,admin,develop.doctor,develop.admin
    - VALIDATION=dns
    - DNSPLUGIN=cloudflare
    - DUCKDNSTOKEN=e68c855a-e1d6-4da3-ac66-0443bc4bf250
    extra_hosts:
    - "host.docker.internal:host-gateway"

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    networks:
    - vaccinations
    restart: unless-stopped
    volumes:
    - /home/flatly/drop_zone:/var/jenkins_home

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    networks:
    - vaccinations
    restart: unless-stopped
    environment:
      PMA_HOST: 'mariadb'

  front-admin:
    container_name: vue
    build:
      dockerfile: containers/vue/Dockerfile
    volumes:
      - /home/flatly/:/app/
    image: vue
    networks: 
      - vaccinations
    restart: unless-stopped

networks:
  vaccinations: